server:
  port: 9090
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/YarismaDB
      username: postgres
      password: Hande0808
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true